require:
  - rubocop-rails

inherit_gem:
  rubocop-discourse: default.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'db/*'
    - 'db/migrate/*'
    - 'notes/*'
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
