require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'db/*'
    - 'db/migrate/*'
    - 'notes/*'
  NewCops: enable

Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
